Assignment 8 rest
asilbektech/html pull request #9
Opened 2023-04-29 00:10 UTC by asilbektech

2023-04-29 03:41 UTC, durdonadev commented on assignments/assignment-8-rest/assignment-7.html
> +            <select name="yourCountry" id="countrySelect">
name should be just "country"

2023-04-29 03:42 UTC, durdonadev commented on assignments/assignment-8-rest/assignment-7.html
> +            <br />
It is better to use div instead of br in this case. Like:
"div" label input "/div"

2023-04-29 03:43 UTC, durdonadev commented on assignments/assignment-8-rest/assignment-7.html
> +                name="yourEmail"
name attr should be "email"

2023-04-29 03:45 UTC, hulkarsharif commented on assignments/assignment-8-rest/assignment-4.html
> +        <title>Document</title>
rename the title Assignment 8.4

2023-04-29 03:46 UTC, durdonadev commented on assignments/assignment-8-rest/assignment-7.html
> +            <label for="fileInput">Upload a Photo</label>
you can use for,id="photoInput" or "imageInput"
name="photo" or "image" are better choices

2023-04-29 03:48 UTC, hulkarsharif commented on assignments/assignment-8-rest/assignment-4.html
> +            <label for="exellentRadio">
id would be excellenRadioInput

2023-04-29 03:49 UTC, hulkarsharif commented on assignments/assignment-8-rest/assignment-4.html
> +            <label for="goodRadio">
for and id must be goodRadioInput

2023-04-29 03:50 UTC, hulkarsharif commented on assignments/assignment-8-rest/assignment-4.html
> +            <label for="averageRadio">
id and for -averageRadioInput

2023-04-29 03:51 UTC, hulkarsharif commented on assignments/assignment-8-rest/assignment-4.html
> +                    name="rateExperience"
name would be better-experience

2023-04-29 03:51 UTC, hulkarsharif commented on assignments/assignment-8-rest/assignment-4.html
> +            <label for="poorRadio">
label for and input id -poorRadioInput

2023-04-29 03:52 UTC, hulkarsharif commented on assignments/assignment-8-rest/assignment-4.html
> +                    name="rateExperience"
the same for name just experience

2023-04-29 03:52 UTC, hulkarsharif commented on assignments/assignment-8-rest/assignment-4.html
> +                    id="veryPoorRadio"
the same

2023-04-29 03:54 UTC, hulkarsharif commented on assignments/assignment-8-rest/assignment-4.html
> +            <button type="submit" id="submitButton">Submit</button>
no need id for submit button
<input type="submit" value="Submit" /> use this

2023-04-30 19:22 UTC, PokizaSdv commented on assignments/assignment-8-rest/assignment-2.html
> +            <label for="rangeInput">Rate your Confidence Level</label>
ratingInput is better idea than rangInput for id and for attr

2023-04-30 19:23 UTC, PokizaSdv commented on assignments/assignment-8-rest/assignment-2.html
> +                <input
use Checkbox for end of for and id attr When using checkbox input

2023-04-30 19:24 UTC, PokizaSdv commented on assignments/assignment-8-rest/assignment-2.html
> +                <input
So historyCategoryCheckbox is good for id and name attr

2023-04-30 19:26 UTC, PokizaSdv commented on assignments/assignment-8-rest/assignment-2.html
> +                    name="quizCategories"
names should be different for checkbox input in this case. 
isHistoryChecked  isScienceChecked isSportChecked isLiteratureChecked for name attrs

2023-04-30 20:11 UTC, durdonadev commented on assignments/assignment-8-rest/assignment-7.html
> +                id="PhotoInput"
use "cemalCase" for id and for attributes

2023-04-30 20:15 UTC, durdonadev commented on assignments/assignment-8-rest/assignment-7.html
> +            <button type="submit" id="submitButton">Submit</button>
use input type submit. and don't use id for submit input

2023-04-30 20:17 UTC, durdonadev commented on assignments/assignment-8-rest/assignment-7.html
> +            <label for="descriptionTextarea"
"photoDescribtionTextarea" is better choice for id and for attributes

2023-05-01 01:39 UTC, ohunazz requested changes

2023-05-01 01:39 UTC, ohunazz commented on assignments/assignment-8-rest/assignment-4.html
>          </form>
Try to use "div" attr

2023-05-02 03:28 UTC, durdonadev approved these changes

2023-05-02 03:58 UTC, PokizaSdv approved these changes

2023-05-02 11:54 UTC, kulievtech commented on assignments/assignment-8-rest/assignment-6.html
> +                name="attending"
attendanceStatus is a better choice for name

2023-05-02 11:54 UTC, kulievtech commented on assignments/assignment-8-rest/assignment-6.html
> +            <label for="numberInput">Number of Guests You Bringing</label>
typo: you are *

2023-05-02 11:59 UTC, kulievtech approved these changes

2023-05-03 21:55 UTC, merged